service: github-copilot-lambda-deployment-test

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  hello:
    handler: src/index.handler
    events:
      - http:
          path: hello
          method: get